#!/usr/bin/env python3
"""Refresh skill collections, marketplace lists, and generated link directories."""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
DOC_SKILLS_DIR = ROOT / "document-skills"
BUILD_DIR = ROOT / "distributions"
ECOSYSTEM_YAML = ROOT / "ecosystem.yaml"


def _find_skill_dirs(base_dir: Path) -> list[Path]:
    return sorted(
        [p.parent for p in base_dir.rglob("SKILL.md") if p.parent != base_dir],
        key=lambda p: p.name,
    )


def _write_list(path: Path, dirs: list[Path]) -> None:
    lines = [str(d.relative_to(ROOT)) for d in dirs]
    content = "\n".join(lines)
    if content:
        content += "\n"
    path.write_text(content, encoding="utf-8")


def _ensure_generated_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    marker = path / ".skills-generated"
    if marker.exists():
        return
    if any(path.iterdir()):
        raise RuntimeError(
            f"Refusing to modify non-empty directory without marker: {path}"
        )
    marker.write_text(
        "generated by scripts/refresh_skill_collections.py\n", encoding="utf-8"
    )


def _sync_links(target_dir: Path, sources: list[Path], mode: str) -> None:
    _ensure_generated_dir(target_dir)

    expected = {src.name: src for src in sources}

    # Remove stale entries (but preserve marker)
    for entry in target_dir.iterdir():
        if entry.name == ".skills-generated":
            continue
        if entry.name not in expected:
            if entry.is_symlink() or entry.is_file():
                entry.unlink()
            elif entry.is_dir():
                shutil.rmtree(entry)

    # Create/update links
    for name, src in expected.items():
        link_path = target_dir / name
        if mode == "copy":
            if link_path.exists() or link_path.is_symlink():
                if link_path.is_symlink() or link_path.is_file():
                    link_path.unlink()
                else:
                    shutil.rmtree(link_path)
            shutil.copytree(src, link_path)
            continue

        # symlink mode
        if link_path.is_symlink():
            resolved = link_path.resolve()
            if resolved == src.resolve():
                continue
            link_path.unlink()
        elif link_path.exists():
            if link_path.is_dir():
                shutil.rmtree(link_path)
            else:
                link_path.unlink()

        rel_src = os.path.relpath(src, target_dir)
        link_path.symlink_to(rel_src, target_is_directory=True)


def _extract_frontmatter(text: str) -> dict[str, str]:
    """Minimal frontmatter extractor (same logic as validate_skills.py)."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}
    data: dict[str, str] = {}
    current_key = None
    for raw in lines[1:end]:
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw.startswith(" ") or raw.startswith("\t"):
            if current_key:
                data[current_key] = f"{data[current_key]}\n{raw.lstrip()}"
            continue
        key, sep, value = raw.partition(":")
        if not sep:
            continue
        current_key = key.strip()
        data[current_key] = value.strip()
    return data


def _write_tier_lists(
    collections_dir: Path, skill_dirs: list[Path],
) -> None:
    """Generate core-skills.txt and community-skills.txt based on tier field."""
    core: list[Path] = []
    community: list[Path] = []
    for d in skill_dirs:
        skill_file = d / "SKILL.md"
        try:
            text = skill_file.read_text(encoding="utf-8")
        except OSError:
            continue
        fm = _extract_frontmatter(text)
        tier = fm.get("tier", "")
        if tier == "core":
            core.append(d)
        elif tier == "community":
            community.append(d)
    _write_list(collections_dir / "core-skills.txt", core)
    _write_list(collections_dir / "community-skills.txt", community)


def _write_governance_lists(
    collections_dir: Path, skill_dirs: list[Path],
) -> None:
    """Generate governance-norms.txt and auto-activate-skills.txt."""
    norms: list[Path] = []
    auto_activate: list[Path] = []
    for d in skill_dirs:
        skill_file = d / "SKILL.md"
        try:
            text = skill_file.read_text(encoding="utf-8")
        except OSError:
            continue
        fm = _extract_frontmatter(text)
        if fm.get("governance_norm_group"):
            norms.append(d)
        if fm.get("governance_auto_activate") == "true":
            auto_activate.append(d)
    _write_list(collections_dir / "governance-norms.txt", norms)
    _write_list(collections_dir / "auto-activate-skills.txt", auto_activate)


def _update_ecosystem_yaml(skill_count: int, category_count: int) -> bool:
    """Update the skill/category counts in ecosystem.yaml. Returns True if the file changed."""
    if not ECOSYSTEM_YAML.exists():
        return False

    text = ECOSYSTEM_YAML.read_text(encoding="utf-8")
    pattern = re.compile(r"\d+\+?\s+skills\s+across\s+\d+\s+categor(?:y|ies)")
    suffix = "category" if category_count == 1 else "categories"
    new_phrase = f"{skill_count} skills across {category_count} {suffix}"

    new_text, n_replacements = pattern.subn(new_phrase, text)
    if n_replacements == 0 or new_text == text:
        return False

    ECOSYSTEM_YAML.write_text(new_text, encoding="utf-8")
    return True


def _update_marketplace(example_paths: list[str], document_paths: list[str]) -> None:
    marketplace_path = ROOT / ".claude-plugin" / "marketplace.json"
    if not marketplace_path.exists():
        return

    data = json.loads(marketplace_path.read_text(encoding="utf-8"))
    plugins = data.get("plugins", [])
    updated = {"example-skills": False, "document-skills": False}

    for plugin in plugins:
        name = plugin.get("name")
        if name == "example-skills":
            plugin["skills"] = [f"./{p}" for p in example_paths]
            updated[name] = True
        elif name == "document-skills":
            plugin["skills"] = [f"./{p}" for p in document_paths]
            updated[name] = True

    if not all(updated.values()):
        missing = [k for k, v in updated.items() if not v]
        raise RuntimeError(f"Missing plugin entries in marketplace.json: {missing}")

    marketplace_path.write_text(
        json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refresh skill collections and generated link directories."
    )
    parser.add_argument(
        "--mode",
        choices=["symlink", "copy"],
        default="copy",
        help="Link strategy for generated skill directories (default: copy).",
    )
    parser.add_argument(
        "--skip-marketplace",
        action="store_true",
        help="Skip updating .claude-plugin/marketplace.json",
    )
    parser.add_argument(
        "--skip-ecosystem",
        action="store_true",
        help="Skip updating ecosystem.yaml skill/category counts",
    )
    args = parser.parse_args()

    example_skill_dirs = _find_skill_dirs(SKILLS_DIR)
    document_skill_dirs = _find_skill_dirs(DOC_SKILLS_DIR)

    collections_dir = BUILD_DIR / "collections"
    collections_dir.mkdir(parents=True, exist_ok=True)

    _write_list(collections_dir / "example-skills.txt", example_skill_dirs)
    _write_list(collections_dir / "document-skills.txt", document_skill_dirs)
    _write_tier_lists(collections_dir, example_skill_dirs + document_skill_dirs)
    _write_governance_lists(collections_dir, example_skill_dirs + document_skill_dirs)

    if not args.skip_marketplace:
        _update_marketplace(
            [str(p.relative_to(ROOT)) for p in example_skill_dirs],
            [str(p.relative_to(ROOT)) for p in document_skill_dirs],
        )

    if not args.skip_ecosystem:
        total_skill_count = len(example_skill_dirs) + len(document_skill_dirs)
        categories = {
            d.relative_to(SKILLS_DIR).parts[0]
            for d in example_skill_dirs
            if SKILLS_DIR in d.parents
        }
        if _update_ecosystem_yaml(total_skill_count, len(categories)):
            print(
                f"Updated ecosystem.yaml: {total_skill_count} skills across "
                f"{len(categories)} categories"
            )

    # Generated link directories in .build/
    _sync_links(BUILD_DIR / "direct" / "example", example_skill_dirs, args.mode)
    _sync_links(BUILD_DIR / "direct" / "document", document_skill_dirs, args.mode)

    _sync_links(BUILD_DIR / "codex" / "skills", example_skill_dirs, args.mode)
    _sync_links(BUILD_DIR / "codex" / "skills-document", document_skill_dirs, args.mode)

    _sync_links(BUILD_DIR / "claude" / "skills", example_skill_dirs, args.mode)
    _sync_links(BUILD_DIR / "claude" / "skills-document", document_skill_dirs, args.mode)

    _sync_links(
        BUILD_DIR / "extensions" / "gemini" / "example-skills" / "skills",
        example_skill_dirs,
        args.mode,
    )
    _sync_links(
        BUILD_DIR / "extensions" / "gemini" / "document-skills" / "skills",
        document_skill_dirs,
        args.mode,
    )

    # Generate registry JSON and lockfile
    scripts_dir = Path(__file__).resolve().parent
    for script_name in ("generate_registry.py", "generate_lockfile.py"):
        script = scripts_dir / script_name
        if script.exists():
            result = subprocess.run(
                [sys.executable, str(script)],
                capture_output=True, text=True,
            )
            if result.returncode != 0:
                print(f"WARNING: {script_name} failed: {result.stderr.strip()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
